baseURL = "https://martinbreuss.com/"
languageCode = "en-us"
theme = "terminal"
pagination.pagerSize = 10

[markup.goldmark.renderer]
  unsafe = true

[params]
  contentTypeName = "posts"
  showMenuItems = 4
  fullWidthTheme = false
  centerTheme = true
  ReadMore = "Read more"

[languages]
  [languages.en]
    title = "Martin Breuss"
    subtitle = "Developing into all directions"
    keywords = "python, web development, data analysis, machine learning"
    copyright = "martinmade 2025"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "mb/home"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog"
        weight = 3
      [[languages.en.menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact"
        weight = 4

[markup]
  [markup.highlight]
    style = "monokai"
    codeFences = true
    lineNos = true
    noClasses = false

